name: GraalVM build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # QUITAMOS OCI_CLI_KEY_CONTENT DE AQUÍ.
      OCI_CLI_USER:        ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY:     ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_REGION:      ${{ secrets.OCI_CLI_REGION }}

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Java version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version || true
      
      # *** PASO CRÍTICO: CREAR EL ARCHIVO DE CLAVE DESDE EL SECRETO ***
      # Este paso se queda, ya que Get or Create OCIR Repo lo necesita.
      - name: Create OCI API Key File
        run: |
          # Reemplaza los caracteres \n por saltos de línea reales y guarda la clave en un archivo
          echo -e "${{ secrets.OCI_CLI_KEY_CONTENT }}" > oci_api_key.pem

      - name: Extract configuration files
        run: |
          cd MtdrSpring
          wget https://objectstorage.mx-queretaro-1.oraclecloud.com/p/9d4QQeajBM0KpBMHJZXxz9dDo4Pj50TlCykE2_1HMkUwjVJAljLkJVcSnpFGm71i/n/axyqsveqbf4z/b/reacttodo-t9ldr/o/deployment_config.tgz
          tar -xzvf deployment_config.tgz
          source env.sh

      # --- CAMBIO IMPORTANTE EN GET-OCIR: USAR 'key_file' ---
      - name: Get or create OCIR repo
        id: get-ocir
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: ${{ secrets.OCI_DOCKER_REPO }}
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
          # Usamos la clave que acabamos de crear:
          key_file: oci_api_key.pem

      - name: Log into OCIR
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          # El login a OCIR solo necesita el auth_token (token de autenticación)
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
          # QUITAMOS key_file de aquí para evitar el error de buffer bounds en esta acción
          
      # --------------------------------------------------------

      - name: Build backend
        run: |
          cd MtdrSpring
          source env.sh
          (cd backend; source build.sh)

      - name: Configure kubectl for OKE
        id: kubectl-oke-action
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
