name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  super-lint:
    name: Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      # Si quieres usar un Checkstyle propio para Java:
      - name: Provide Checkstyle config (optional)
        run: |
          mkdir -p /action/lib/.automation/
          cp .github/linters/java_checks.xml /action/lib/.automation/
        # ^ coloca tu archivo en .github/linters/java_checks.xml en el repo

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Analiza solo cambios (por defecto). Pon "true" si quieres todo el repo.
          VALIDATE_ALL_CODEBASE: "false"

          # Activa lo que usas normalmente
          VALIDATE_JAVA: "true"
          VALIDATE_GOOGLE_JAVA_FORMAT: "true"
          JAVA_FILE_NAME: "java_checks.xml"   # <— Debe coincidir con el archivo copiado arriba
          VALIDATE_HTML: "true"
          VALIDATE_CSS: "true"
          VALIDATE_JAVASCRIPT_ES: "true"
          VALIDATE_TYPESCRIPT_ES: "true"
          VALIDATE_JSON: "true"
          VALIDATE_YAML: "true"
          VALIDATE_MARKDOWN: "true"
          VALIDATE_DOCKERFILE_HADOLINT: "true"
          VALIDATE_GITLEAKS: "true"

          # (Opcional) si guardas reglas en otra carpeta del repo:
          # LINTER_RULES_PATH: ".github/linters"
